"""empty message

Revision ID: f0432f4e9988
Revises: 
Create Date: 2020-07-01 10:14:58.225011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0432f4e9988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('building_image', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('number_of_bedroom', sa.Integer(), nullable=False),
    sa.Column('number_of_living_room', sa.Integer(), nullable=False),
    sa.Column('number_of_bathroom', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.Boolean(), nullable=True),
    sa.Column('type_of_rental', sa.String(length=120), nullable=True),
    sa.Column('rent_price', sa.Integer(), nullable=False),
    sa.Column('unit_image', sa.String(length=500), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit')
    op.drop_table('building')
    # ### end Alembic commands ###
